[tox]
env_list = format, lint, unit
skip_missing_interpreters = True

[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests
all_paths = {[vars]src_path} {[vars]tests_path}

[testenv]
set_env =
    PYTHONPATH = {tox_root}/src
    PYTHONBREAKPOINT=pdb.set_trace
    PY_COLORS=1
pass_env =
    PYTHONPATH
    HOME
    PATH
    MODEL_SETTINGS

[testenv:format]
description = Apply coding style standards to code
deps =
    ruff
commands =
    ruff format {[vars]all_paths}
    ruff check --fix {[vars]all_paths}

[testenv:lint]
description = Check code against coding style standards
deps =
    ruff
    mypy
    types-requests
commands =
    ruff check {[vars]all_paths}
    ruff format --check --diff {[vars]all_paths}
    mypy {[vars]src_path}

[testenv:unit]
description = Run unit tests
deps =
    pytest
    pytest-asyncio
    coverage[toml]
    ops[testing]
    -e .[testing]
commands =
    coverage run --source={[vars]src_path} -m pytest {[vars]tests_path}/unit -v --tb=short
    coverage report --show-missing
    coverage html --directory=htmlcov
    coverage xml

[testenv:integration]
description = Run integration tests
deps =
    pytest
    pytest-asyncio
    jubilant
    juju
commands =
    pytest {[vars]tests_path}/integration -v --tb=short --log-cli-level=INFO

[testenv:dev]
description = Development environment
deps =
    {[testenv:lint]deps}
    {[testenv:unit]deps}
    {[testenv:integration]deps}
    ipython
commands = {posargs}