#!/usr/bin/env python3
# Copyright 2025 Ubuntu
# See LICENSE file for licensing details.

"""Integration tests for Mosquitto charm using Jubilant."""

import subprocess
import tempfile
from pathlib import Path

import pytest
import yaml
from jubilant import Juju

METADATA = yaml.safe_load(Path("./charmcraft.yaml").read_text())
APP_NAME = METADATA["name"]


class TestMosquittoCharmIntegration:
    """Integration tests for Mosquitto charm."""

    @pytest.fixture(scope="class")
    def juju(self):
        """Create a Juju instance for testing."""
        return Juju()

    @pytest.fixture(scope="class")
    def charm_file(self):
        """Build the charm and return the path to the .charm file."""
        subprocess.run(["charmcraft", "pack"], capture_output=True, text=True, check=True)

        # Find the generated .charm file
        charm_files = list(Path(".").glob("*.charm"))
        if not charm_files:
            pytest.fail("No .charm file found after packing")

        return str(charm_files[0])

    def test_deploy_mosquitto_charm(self, juju: Juju, charm_file: str):
        """Test deploying the Mosquitto charm."""
        # Deploy the charm
        juju.deploy(charm_file, application_name=APP_NAME)

        # Wait for the application to become active
        juju.wait_for_idle([APP_NAME], status="active", timeout=600)

        # Verify the application is deployed
        status = juju.status(format="json")
        applications = status["applications"]

        assert APP_NAME in applications
        assert applications[APP_NAME]["status"]["status"] == "active"

    def test_mosquitto_service_running(self, juju: Juju):
        """Test that Mosquitto service is actually running."""
        # Check that mosquitto process is running on the unit
        result = juju.ssh(f"{APP_NAME}/0", ["systemctl", "is-active", "mosquitto"])
        assert result.stdout.strip() == "active"

    def test_mosquitto_port_listening(self, juju: Juju):
        """Test that Mosquitto is listening on the configured port."""
        # Check that port 1883 is listening
        result = juju.ssh(f"{APP_NAME}/0", ["ss", "-tlnp", "|", "grep", ":1883"])
        assert ":1883" in result.stdout

    def test_mosquitto_config_file_exists(self, juju: Juju):
        """Test that Mosquitto configuration file exists and is valid."""
        # Check that config file exists
        result = juju.ssh(f"{APP_NAME}/0", ["test", "-f", "/etc/mosquitto/mosquitto.conf"])
        assert result.returncode == 0

        # Check config file contains expected content
        result = juju.ssh(f"{APP_NAME}/0", ["cat", "/etc/mosquitto/mosquitto.conf"])
        config_content = result.stdout

        assert "port 1883" in config_content
        assert "# Mosquitto configuration file generated by Juju charm" in config_content

    def test_mosquitto_client_connection(self, juju: Juju):
        """Test that MQTT clients can connect to the broker."""
        # Test basic connection using mosquitto_pub/sub
        with tempfile.NamedTemporaryFile(mode="w", suffix=".sh", delete=False) as f:
            f.write("""#!/bin/bash
# Test MQTT connection
timeout 10 mosquitto_sub -h localhost -p 1883 -t test/topic -C 1 &
sleep 2
mosquitto_pub -h localhost -p 1883 -t test/topic -m "test message"
wait
""")
            script_path = f.name

        # Copy script to unit and run it
        juju.scp(script_path, f"{APP_NAME}/0:/tmp/mqtt_test.sh")
        juju.ssh(f"{APP_NAME}/0", ["chmod", "+x", "/tmp/mqtt_test.sh"])
        result = juju.ssh(f"{APP_NAME}/0", ["/tmp/mqtt_test.sh"])

        # Should see the test message
        assert "test message" in result.stdout

    def test_restart_action(self, juju: Juju):
        """Test the restart action works correctly."""
        # Run the restart action
        action_id = juju.run_action(f"{APP_NAME}/0", "restart")

        # Wait for action to complete
        result = juju.show_action(action_id, wait=30)

        assert result["status"] == "completed"
        assert "Mosquitto restarted successfully" in result["results"]["result"]

    def test_get_status_action(self, juju: Juju):
        """Test the get-status action returns useful information."""
        # Run the get-status action
        action_id = juju.run_action(f"{APP_NAME}/0", "get-status")

        # Wait for action to complete
        result = juju.show_action(action_id, wait=30)

        assert result["status"] == "completed"
        assert "service-status" in result["results"]
        assert "version" in result["results"]

    def test_config_change_port(self, juju: Juju):
        """Test changing the MQTT port configuration."""
        # Change port to 1884
        juju.config(APP_NAME, {"port": "1884"})

        # Wait for the change to be applied
        juju.wait_for_idle([APP_NAME], status="active", timeout=300)

        # Check that the new port is listening
        result = juju.ssh(f"{APP_NAME}/0", ["ss", "-tlnp", "|", "grep", ":1884"])
        assert ":1884" in result.stdout

        # Check that old port is no longer listening
        result = juju.ssh(f"{APP_NAME}/0", ["ss", "-tlnp", "|", "grep", ":1883"])
        assert result.returncode != 0 or ":1883" not in result.stdout

        # Reset port back to default
        juju.config(APP_NAME, {"port": "1883"})
        juju.wait_for_idle([APP_NAME], status="active", timeout=300)

    def test_config_anonymous_access(self, juju: Juju):
        """Test enabling anonymous access configuration."""
        # Enable anonymous access
        juju.config(APP_NAME, {"allow-anonymous": "true"})

        # Wait for the change to be applied
        juju.wait_for_idle([APP_NAME], status="active", timeout=300)

        # Check config file was updated
        result = juju.ssh(
            f"{APP_NAME}/0", ["grep", "allow_anonymous", "/etc/mosquitto/mosquitto.conf"]
        )
        assert "allow_anonymous true" in result.stdout

        # Reset to default
        juju.config(APP_NAME, {"allow-anonymous": "false"})
        juju.wait_for_idle([APP_NAME], status="active", timeout=300)

    def test_websockets_configuration(self, juju: Juju):
        """Test WebSocket listener configuration."""
        # WebSockets should be enabled by default on port 9001
        result = juju.ssh(f"{APP_NAME}/0", ["ss", "-tlnp", "|", "grep", ":9001"])
        assert ":9001" in result.stdout

        # Check config file contains websocket configuration
        result = juju.ssh(
            f"{APP_NAME}/0", ["grep", "-A1", "listener 9001", "/etc/mosquitto/mosquitto.conf"]
        )
        assert "protocol websockets" in result.stdout

    @pytest.fixture(scope="class", autouse=True)
    def cleanup(self, juju: Juju):
        """Clean up after tests."""
        yield

        # Remove the application
        try:
            juju.remove_application(APP_NAME, force=True)
            juju.wait_for_idle([], timeout=300)
        except Exception:
            pass  # Best effort cleanup
