"""Mosquitto workload management module."""

import logging
import os
import subprocess
import tempfile
from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class MosquittoError(Exception):
    """Exception raised for Mosquitto-related errors."""
    pass


class MosquittoManager:
    """Manager for Mosquitto MQTT broker operations."""
    
    def __init__(self):
        self.service_name = "mosquitto"
        self.config_path = Path("/etc/mosquitto/mosquitto.conf")
        self.password_file = Path("/etc/mosquitto/passwd")
        self.log_file = Path("/var/log/mosquitto/mosquitto.log")
        self.pid_file = Path("/var/run/mosquitto.pid")
    
    def install(self) -> None:
        """Install Mosquitto and required packages."""
        logger.info("Installing Mosquitto packages")
        
        try:
            # Update package list
            self._run_command(["apt", "update"])
            
            # Install mosquitto and mosquitto-clients
            self._run_command([
                "apt", "install", "-y", 
                "mosquitto", 
                "mosquitto-clients"
            ])
            
            # Create necessary directories
            os.makedirs("/var/log/mosquitto", exist_ok=True)
            os.makedirs("/var/lib/mosquitto", exist_ok=True)
            
            # Set proper permissions
            self._run_command(["chown", "-R", "mosquitto:mosquitto", "/var/lib/mosquitto"])
            self._run_command(["chown", "-R", "mosquitto:mosquitto", "/var/log/mosquitto"])
            
            logger.info("Mosquitto installation completed")
            
        except subprocess.CalledProcessError as e:
            raise MosquittoError(f"Failed to install Mosquitto: {e}")
    
    def configure(self, config) -> None:
        """Configure Mosquitto with the provided settings."""
        logger.info("Configuring Mosquitto")
        
        try:
            self._write_config_file(config)
            self._setup_logging(config.log_level)
            
            # Ensure configuration directory exists and has correct permissions
            config_dir = self.config_path.parent
            config_dir.mkdir(exist_ok=True)
            self._run_command(["chown", "-R", "mosquitto:mosquitto", str(config_dir)])
            
            logger.info("Mosquitto configuration completed")
            
        except Exception as e:
            raise MosquittoError(f"Failed to configure Mosquitto: {e}")
    
    def _write_config_file(self, config) -> None:
        """Write the Mosquitto configuration file."""
        config_content = self._generate_config_content(config)
        
        # Write to temporary file first, then move to final location
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.conf') as tmp_file:
            tmp_file.write(config_content)
            tmp_config_path = tmp_file.name
        
        try:
            # Move temporary file to final location
            self._run_command(["mv", tmp_config_path, str(self.config_path)])
            self._run_command(["chown", "mosquitto:mosquitto", str(self.config_path)])
            self._run_command(["chmod", "644", str(self.config_path)])
        except subprocess.CalledProcessError as e:
            # Clean up temporary file if move fails
            Path(tmp_config_path).unlink(missing_ok=True)
            raise MosquittoError(f"Failed to write config file: {e}")
    
    def _generate_config_content(self, config) -> str:
        """Generate Mosquitto configuration file content."""
        lines = [
            "# Mosquitto configuration file generated by Juju charm",
            f"# Generated on {datetime.now().isoformat()}",
            "",
            "# Basic settings",
            f"port {config.port}",
            f"max_connections {config.max_connections}",
            f"keepalive_interval {config.keepalive}",
            f"message_size_limit {config.message_size_limit}",
            "",
            "# Persistence settings",
        ]
        
        if config.persistence:
            lines.extend([
                "persistence true",
                f"persistence_location {config.persistence_location}/",
                "autosave_interval 1800",
                "persistence_file mosquitto.db",
            ])
        else:
            lines.append("persistence false")
        
        lines.extend([
            "",
            "# Logging settings",
            f"log_dest file /var/log/mosquitto/mosquitto.log",
            f"log_type error",
            f"log_type warning",
        ])
        
        if config.log_level in ("info", "debug"):
            lines.append("log_type information")
        if config.log_level == "debug":
            lines.extend([
                "log_type debug",
                "log_type subscribe",
                "log_type unsubscribe",
            ])
        
        lines.extend([
            "",
            "# Authentication settings",
        ])
        
        if config.allow_anonymous:
            lines.append("allow_anonymous true")
        else:
            lines.extend([
                "allow_anonymous false",
                f"password_file {self.password_file}",
            ])
        
        # WebSocket support
        lines.extend([
            "",
            "# WebSocket support",
            f"listener {config.websockets_port}",
            "protocol websockets",
        ])
        
        return "\n".join(lines) + "\n"
    
    def _setup_logging(self, log_level: str) -> None:
        """Set up logging directory and permissions."""
        log_dir = self.log_file.parent
        log_dir.mkdir(exist_ok=True)
        
        # Ensure log file exists and has correct permissions
        if not self.log_file.exists():
            self.log_file.touch()
        
        self._run_command(["chown", "-R", "mosquitto:mosquitto", str(log_dir)])
        self._run_command(["chmod", "755", str(log_dir)])
        self._run_command(["chmod", "644", str(self.log_file)])
    
    def start(self) -> None:
        """Start the Mosquitto service."""
        logger.info("Starting Mosquitto service")
        
        try:
            self._run_command(["systemctl", "enable", self.service_name])
            self._run_command(["systemctl", "start", self.service_name])
            
            # Wait a moment and check if service started successfully
            import time
            time.sleep(2)
            
            if not self.is_running():
                raise MosquittoError("Service failed to start")
            
            logger.info("Mosquitto service started successfully")
            
        except subprocess.CalledProcessError as e:
            raise MosquittoError(f"Failed to start Mosquitto service: {e}")
    
    def stop(self) -> None:
        """Stop the Mosquitto service."""
        logger.info("Stopping Mosquitto service")
        
        try:
            self._run_command(["systemctl", "stop", self.service_name])
            logger.info("Mosquitto service stopped successfully")
            
        except subprocess.CalledProcessError as e:
            raise MosquittoError(f"Failed to stop Mosquitto service: {e}")
    
    def restart(self) -> None:
        """Restart the Mosquitto service."""
        logger.info("Restarting Mosquitto service")
        
        try:
            self._run_command(["systemctl", "restart", self.service_name])
            
            # Wait a moment and check if service restarted successfully
            import time
            time.sleep(2)
            
            if not self.is_running():
                raise MosquittoError("Service failed to restart")
            
            logger.info("Mosquitto service restarted successfully")
            
        except subprocess.CalledProcessError as e:
            raise MosquittoError(f"Failed to restart Mosquitto service: {e}")
    
    def is_running(self) -> bool:
        """Check if Mosquitto service is running."""
        try:
            result = self._run_command(
                ["systemctl", "is-active", self.service_name],
                capture_output=True
            )
            return result.stdout.strip() == "active"
        except subprocess.CalledProcessError:
            return False
    
    def reload_config(self) -> None:
        """Reload Mosquitto configuration without restarting."""
        logger.info("Reloading Mosquitto configuration")
        
        try:
            # Send SIGHUP to reload configuration
            self._run_command(["systemctl", "reload", self.service_name])
            logger.info("Mosquitto configuration reloaded successfully")
            
        except subprocess.CalledProcessError as e:
            # If reload fails, try restart as fallback
            logger.warning(f"Config reload failed, attempting restart: {e}")
            self.restart()
    
    def get_stats(self) -> Dict[str, Any]:
        """Get Mosquitto broker statistics."""
        logger.info("Retrieving Mosquitto statistics")
        
        stats = {
            "service_status": "active" if self.is_running() else "inactive",
            "config_file": str(self.config_path),
            "log_file": str(self.log_file),
            "pid_file": str(self.pid_file),
        }
        
        # Add basic service information
        try:
            result = self._run_command(
                ["systemctl", "show", self.service_name, "--property=MainPID,ActiveState,LoadState"],
                capture_output=True
            )
            for line in result.stdout.strip().split('\n'):
                if '=' in line:
                    key, value = line.split('=', 1)
                    stats[key.lower()] = value
        except subprocess.CalledProcessError:
            logger.warning("Could not retrieve systemctl status")
        
        # Add log file size if it exists
        if self.log_file.exists():
            stats["log_size_bytes"] = self.log_file.stat().st_size
        
        return stats
    
    def add_user(self, username: str, password: str) -> None:
        """Add a new MQTT user."""
        logger.info(f"Adding user: {username}")
        
        try:
            # Create password file if it doesn't exist
            if not self.password_file.exists():
                self.password_file.touch()
                self._run_command(["chown", "mosquitto:mosquitto", str(self.password_file)])
                self._run_command(["chmod", "600", str(self.password_file)])
            
            # Add user with mosquitto_passwd
            self._run_command([
                "mosquitto_passwd", "-b", str(self.password_file), username, password
            ])
            
            logger.info(f"User {username} added successfully")
            
        except subprocess.CalledProcessError as e:
            raise MosquittoError(f"Failed to add user {username}: {e}")
    
    def remove_user(self, username: str) -> None:
        """Remove an MQTT user."""
        logger.info(f"Removing user: {username}")
        
        try:
            if not self.password_file.exists():
                raise MosquittoError("Password file does not exist")
            
            # Remove user with mosquitto_passwd
            self._run_command([
                "mosquitto_passwd", "-D", str(self.password_file), username
            ])
            
            logger.info(f"User {username} removed successfully")
            
        except subprocess.CalledProcessError as e:
            raise MosquittoError(f"Failed to remove user {username}: {e}")
    
    def list_users(self) -> List[str]:
        """List all configured MQTT users."""
        logger.info("Listing MQTT users")
        
        try:
            if not self.password_file.exists():
                return []
            
            with open(self.password_file, 'r') as f:
                users = []
                for line in f:
                    line = line.strip()
                    if line and ':' in line:
                        username = line.split(':', 1)[0]
                        users.append(username)
                
                return users
                
        except Exception as e:
            raise MosquittoError(f"Failed to list users: {e}")
    
    def backup_data(self) -> str:
        """Backup Mosquitto data and configuration."""
        logger.info("Creating Mosquitto backup")
        
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            backup_dir = f"/tmp/mosquitto_backup_{timestamp}"
            
            # Create backup directory
            os.makedirs(backup_dir, exist_ok=True)
            
            # Backup configuration files
            if self.config_path.exists():
                self._run_command(["cp", str(self.config_path), backup_dir])
            
            if self.password_file.exists():
                self._run_command(["cp", str(self.password_file), backup_dir])
            
            # Backup persistence data
            persistence_dir = Path("/var/lib/mosquitto")
            if persistence_dir.exists():
                self._run_command([
                    "cp", "-r", str(persistence_dir), 
                    os.path.join(backup_dir, "persistence")
                ])
            
            # Create tar archive
            backup_file = f"/tmp/mosquitto_backup_{timestamp}.tar.gz"
            self._run_command([
                "tar", "-czf", backup_file, "-C", "/tmp", 
                f"mosquitto_backup_{timestamp}"
            ])
            
            # Clean up temporary directory
            self._run_command(["rm", "-rf", backup_dir])
            
            logger.info(f"Backup created: {backup_file}")
            return backup_file
            
        except Exception as e:
            raise MosquittoError(f"Failed to create backup: {e}")
    
    def restore_data(self, backup_path: str) -> None:
        """Restore Mosquitto data from backup."""
        logger.info(f"Restoring Mosquitto from backup: {backup_path}")
        
        try:
            if not Path(backup_path).exists():
                raise MosquittoError(f"Backup file not found: {backup_path}")
            
            # Stop service before restore
            was_running = self.is_running()
            if was_running:
                self.stop()
            
            # Extract backup to temporary directory
            temp_dir = "/tmp/mosquitto_restore"
            os.makedirs(temp_dir, exist_ok=True)
            
            self._run_command([
                "tar", "-xzf", backup_path, "-C", temp_dir, "--strip-components=1"
            ])
            
            # Restore configuration files
            config_backup = Path(temp_dir) / "mosquitto.conf"
            if config_backup.exists():
                self._run_command(["cp", str(config_backup), str(self.config_path)])
                self._run_command(["chown", "mosquitto:mosquitto", str(self.config_path)])
            
            passwd_backup = Path(temp_dir) / "passwd"
            if passwd_backup.exists():
                self._run_command(["cp", str(passwd_backup), str(self.password_file)])
                self._run_command(["chown", "mosquitto:mosquitto", str(self.password_file)])
                self._run_command(["chmod", "600", str(self.password_file)])
            
            # Restore persistence data
            persistence_backup = Path(temp_dir) / "persistence"
            if persistence_backup.exists():
                persistence_dir = Path("/var/lib/mosquitto")
                if persistence_dir.exists():
                    self._run_command(["rm", "-rf", str(persistence_dir)])
                
                self._run_command(["cp", "-r", str(persistence_backup), str(persistence_dir)])
                self._run_command(["chown", "-R", "mosquitto:mosquitto", str(persistence_dir)])
            
            # Clean up temporary directory
            self._run_command(["rm", "-rf", temp_dir])
            
            # Restart service if it was running
            if was_running:
                self.start()
            
            logger.info("Restore completed successfully")
            
        except Exception as e:
            raise MosquittoError(f"Failed to restore from backup: {e}")
    
    def _run_command(self, command: List[str], capture_output: bool = False, 
                     input_data: Optional[str] = None) -> subprocess.CompletedProcess:
        """Run a system command safely."""
        try:
            kwargs = {
                'check': True,
                'text': True,
            }
            
            if capture_output:
                kwargs['capture_output'] = True
            
            if input_data:
                kwargs['input'] = input_data
            
            logger.debug(f"Running command: {' '.join(command)}")
            return subprocess.run(command, **kwargs)
            
        except subprocess.CalledProcessError as e:
            logger.error(f"Command failed: {' '.join(command)}")
            logger.error(f"Return code: {e.returncode}")
            if hasattr(e, 'stdout') and e.stdout:
                logger.error(f"stdout: {e.stdout}")
            if hasattr(e, 'stderr') and e.stderr:
                logger.error(f"stderr: {e.stderr}")
            raise