# Copyright 2025 Ubuntu
# See LICENSE file for licensing details.

"""Functions for managing and interacting with the workload.

The intention is that this module could be used outside the context of a charm.
"""

import logging
import pathlib
import subprocess
import time
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from charm import MosquittoConfig

logger = logging.getLogger(__name__)

MOSQUITTO_CONFIG_PATH = pathlib.Path("/etc/mosquitto/mosquitto.conf")
MOSQUITTO_DATA_DIR = pathlib.Path("/var/lib/mosquitto")
MOSQUITTO_LOG_DIR = pathlib.Path("/var/log/mosquitto")


def install() -> None:
    """Install Mosquitto MQTT broker using apt."""
    logger.info("Installing Mosquitto MQTT broker")
    subprocess.run(["apt", "update"], check=True, capture_output=True)

    subprocess.run(
        ["apt", "install", "-y", "mosquitto", "mosquitto-clients"], check=True, capture_output=True
    )

    # Ensure directories exist
    MOSQUITTO_DATA_DIR.mkdir(parents=True, exist_ok=True)
    MOSQUITTO_LOG_DIR.mkdir(parents=True, exist_ok=True)

    # Set ownership for mosquitto user
    subprocess.run(
        ["chown", "-R", "mosquitto:mosquitto", str(MOSQUITTO_DATA_DIR)],
        check=True,
        capture_output=True,
    )

    subprocess.run(
        ["chown", "-R", "mosquitto:mosquitto", str(MOSQUITTO_LOG_DIR)],
        check=True,
        capture_output=True,
    )


def configure(config: "MosquittoConfig") -> None:
    """Configure Mosquitto with the provided settings."""
    logger.info("Configuring Mosquitto")

    config_content = _generate_config(config)

    # Write configuration file
    MOSQUITTO_CONFIG_PATH.write_text(config_content)

    # Set proper permissions
    subprocess.run(
        ["chown", "mosquitto:mosquitto", str(MOSQUITTO_CONFIG_PATH)],
        check=True,
        capture_output=True,
    )


def _generate_config(config: "MosquittoConfig") -> str:
    """Generate Mosquitto configuration file content."""
    config_lines = [
        "# Mosquitto configuration file generated by Juju charm",
        "",
        f"port {config.port}",
        f"log_dest file {MOSQUITTO_LOG_DIR}/mosquitto.log",
        f"log_type {config.log_level}",
    ]

    if config.persistence:
        config_lines.extend(
            [
                "persistence true",
                f"persistence_location {MOSQUITTO_DATA_DIR}/",
            ]
        )
    else:
        config_lines.append("persistence false")

    if config.max_connections > 0:
        config_lines.append(f"max_connections {config.max_connections}")

    if config.message_size_limit > 0:
        config_lines.append(f"message_size_limit {config.message_size_limit}")

    config_lines.append(f"allow_anonymous {str(config.allow_anonymous).lower()}")

    if config.websockets_port > 0:
        config_lines.extend(
            [
                "",
                f"listener {config.websockets_port}",
                "protocol websockets",
            ]
        )

    return "\n".join(config_lines) + "\n"


def start() -> None:
    """Start Mosquitto service."""
    logger.info("Starting Mosquitto service")
    subprocess.run(["systemctl", "enable", "mosquitto"], check=True, capture_output=True)

    subprocess.run(["systemctl", "start", "mosquitto"], check=True, capture_output=True)

    # Wait for service to be ready
    _wait_for_service()


def stop() -> None:
    """Stop Mosquitto service."""
    logger.info("Stopping Mosquitto service")
    subprocess.run(["systemctl", "stop", "mosquitto"], check=True, capture_output=True)


def restart() -> None:
    """Restart Mosquitto service."""
    logger.info("Restarting Mosquitto service")
    subprocess.run(["systemctl", "restart", "mosquitto"], check=True, capture_output=True)

    # Wait for service to be ready
    _wait_for_service()


def _wait_for_service() -> None:
    """Wait for Mosquitto service to be ready."""
    for _ in range(30):  # Wait up to 30 seconds
        try:
            result = subprocess.run(
                ["systemctl", "is-active", "mosquitto"], capture_output=True, text=True
            )
            if result.returncode == 0 and result.stdout.strip() == "active":
                return
        except subprocess.SubprocessError:
            pass
        time.sleep(1)

    raise RuntimeError("Mosquitto service failed to start within 30 seconds")


def get_version() -> str | None:
    """Get the running version of Mosquitto."""
    try:
        result = subprocess.run(["mosquitto", "-h"], capture_output=True, text=True)

        # Parse version from help output
        for line in result.stderr.split("\n"):
            if "mosquitto version" in line:
                parts = line.split()
                if len(parts) >= 3:
                    return parts[2]

        return None
    except subprocess.SubprocessError:
        logger.exception("Failed to get Mosquitto version")
        return None


def get_status() -> dict[str, str]:
    """Get Mosquitto service status and statistics."""
    try:
        # Check systemctl status
        systemctl_result = subprocess.run(
            ["systemctl", "is-active", "mosquitto"], capture_output=True, text=True
        )

        service_status = systemctl_result.stdout.strip()

        # Get service details
        status_result = subprocess.run(
            ["systemctl", "status", "mosquitto", "--no-pager", "--lines=0"],
            capture_output=True,
            text=True,
        )

        status_info = {
            "service-status": service_status,
            "version": get_version() or "unknown",
        }

        # Extract additional info from status output
        for line in status_result.stdout.split("\n"):
            line = line.strip()
            if "Active:" in line:
                status_info["active-since"] = line.split("Active:")[1].strip()
            elif "Main PID:" in line:
                status_info["main-pid"] = line.split("Main PID:")[1].strip()

        return status_info

    except subprocess.SubprocessError:
        logger.exception("Failed to get Mosquitto status")
        return {"service-status": "unknown", "error": "Failed to get status"}
