# Copyright 2025 Ubuntu
# See LICENSE file for licensing details.

"""Functions for managing and interacting with the workload.

The intention is that this module could be used outside the context of a charm.
"""

import datetime
import logging
import os
import pathlib
import shutil
import subprocess
import tempfile
import time
from typing import TYPE_CHECKING

import opentelemetry.trace
from charms.operator_libs_linux.v0 import apt
from charms.operator_libs_linux.v1 import systemd

if TYPE_CHECKING:
    from charm import MosquittoConfig

logger = logging.getLogger(__name__)
tracer = opentelemetry.trace.get_tracer(__name__)

MOSQUITTO_CONFIG_PATH = pathlib.Path("/etc/mosquitto/mosquitto.conf")
MOSQUITTO_DATA_DIR = pathlib.Path("/var/lib/mosquitto")
MOSQUITTO_LOG_DIR = pathlib.Path("/var/log/mosquitto")
MOSQUITTO_CERTS_DIR = pathlib.Path("/etc/mosquitto/certs")
MOSQUITTO_AUTH_DIR = pathlib.Path("/etc/mosquitto/auth")
MOSQUITTO_BACKUP_DIR = pathlib.Path("/var/backup/mosquitto")


def install() -> None:
    """Install Mosquitto MQTT broker using apt."""
    with tracer.start_as_current_span("mosquitto_install_packages"):
        span = opentelemetry.trace.get_current_span()
        logger.info("Installing Mosquitto MQTT broker")
        span.add_event("Starting package installation")

        apt.update()
        span.add_event("APT update completed")

        apt.add_package(["mosquitto", "mosquitto-clients"])
        span.add_event("Mosquitto packages installed")

    # Ensure directories exist
    MOSQUITTO_DATA_DIR.mkdir(parents=True, exist_ok=True)
    MOSQUITTO_LOG_DIR.mkdir(parents=True, exist_ok=True)

    # Set ownership for mosquitto user
    subprocess.run(
        ["chown", "-R", "mosquitto:mosquitto", str(MOSQUITTO_DATA_DIR)],
        check=True,
        capture_output=True,
    )

    subprocess.run(
        ["chown", "-R", "mosquitto:mosquitto", str(MOSQUITTO_LOG_DIR)],
        check=True,
        capture_output=True,
    )


def configure(config: "MosquittoConfig") -> None:
    """Configure Mosquitto with the provided settings."""
    logger.info("Configuring Mosquitto")

    config_content = _generate_config(config)

    # Write configuration file
    MOSQUITTO_CONFIG_PATH.write_text(config_content)

    # Set proper permissions
    subprocess.run(
        ["chown", "mosquitto:mosquitto", str(MOSQUITTO_CONFIG_PATH)],
        check=True,
        capture_output=True,
    )


def _generate_config(config: "MosquittoConfig") -> str:
    """Generate Mosquitto configuration file content."""
    config_lines = [
        "# Mosquitto configuration file generated by Juju charm",
        "",
        f"port {config.port}",
        f"log_dest file {MOSQUITTO_LOG_DIR}/mosquitto.log",
        f"log_type {config.log_level}",
    ]

    _add_persistence_config(config_lines, config)
    _add_limits_config(config_lines, config)
    _add_auth_config(config_lines, config)
    _add_websocket_config(config_lines, config)
    _add_tls_config(config_lines, config)

    return "\n".join(config_lines) + "\n"


def _add_persistence_config(config_lines: list[str], config: "MosquittoConfig") -> None:
    """Add persistence configuration to config lines."""
    if config.persistence:
        config_lines.extend(
            [
                "persistence true",
                f"persistence_location {MOSQUITTO_DATA_DIR}/",
            ]
        )
    else:
        config_lines.append("persistence false")


def _add_limits_config(config_lines: list[str], config: "MosquittoConfig") -> None:
    """Add connection and message limits to config lines."""
    if config.max_connections > 0:
        config_lines.append(f"max_connections {config.max_connections}")

    if config.message_size_limit > 0:
        config_lines.append(f"message_size_limit {config.message_size_limit}")


def _add_auth_config(config_lines: list[str], config: "MosquittoConfig") -> None:
    """Add authentication configuration to config lines."""
    config_lines.append(f"allow_anonymous {str(config.allow_anonymous).lower()}")

    if config.password_file_path:
        config_lines.append(f"password_file {config.password_file_path}")

    if config.acl_file_path:
        config_lines.append(f"acl_file {config.acl_file_path}")


def _add_websocket_config(config_lines: list[str], config: "MosquittoConfig") -> None:
    """Add WebSocket listener configuration to config lines."""
    if config.websockets_port > 0:
        config_lines.extend(
            [
                "",
                f"listener {config.websockets_port}",
                "protocol websockets",
            ]
        )


def _add_tls_config(config_lines: list[str], config: "MosquittoConfig") -> None:
    """Add TLS configuration to config lines."""
    # TLS listener
    if config.tls_port > 0 and config.server_cert_path and config.server_key_path:
        config_lines.extend(
            [
                "",
                "# TLS listener",
                f"listener {config.tls_port}",
                f"certfile {config.server_cert_path}",
                f"keyfile {config.server_key_path}",
            ]
        )

        if config.ca_cert_path:
            config_lines.append(f"cafile {config.ca_cert_path}")
            config_lines.append("require_certificate true")

    # TLS WebSocket listener
    if config.tls_websockets_port > 0 and config.server_cert_path and config.server_key_path:
        config_lines.extend(
            [
                "",
                "# TLS WebSocket listener",
                f"listener {config.tls_websockets_port}",
                "protocol websockets",
                f"certfile {config.server_cert_path}",
                f"keyfile {config.server_key_path}",
            ]
        )

        if config.ca_cert_path:
            config_lines.append(f"cafile {config.ca_cert_path}")


def start() -> None:
    """Start Mosquitto service."""
    logger.info("Starting Mosquitto service")
    systemd.service_enable("mosquitto")
    systemd.service_start("mosquitto")

    # Wait for service to be ready
    _wait_for_service()


def stop() -> None:
    """Stop Mosquitto service."""
    logger.info("Stopping Mosquitto service")
    systemd.service_stop("mosquitto")


def restart() -> None:
    """Restart Mosquitto service."""
    logger.info("Restarting Mosquitto service")
    systemd.service_restart("mosquitto")

    # Wait for service to be ready
    _wait_for_service()


def _wait_for_service() -> None:
    """Wait for Mosquitto service to be ready."""
    for _ in range(30):  # Wait up to 30 seconds
        try:
            if systemd.service_running("mosquitto"):
                return
        except Exception:
            pass
        time.sleep(1)

    raise RuntimeError("Mosquitto service failed to start within 30 seconds")


def get_version() -> str | None:
    """Get the running version of Mosquitto."""
    try:
        result = subprocess.run(["mosquitto", "-h"], capture_output=True, text=True)

        # Parse version from help output
        for line in result.stderr.split("\n"):
            if "mosquitto version" in line:
                parts = line.split()
                if len(parts) >= 3:
                    return parts[2]

        return None
    except subprocess.SubprocessError:
        logger.exception("Failed to get Mosquitto version")
        return None


def get_status() -> dict[str, str]:
    """Get Mosquitto service status and statistics."""
    try:
        # Check service status using systemd lib
        is_running = systemd.service_running("mosquitto")
        service_status = "active" if is_running else "inactive"

        status_info = {
            "service-status": service_status,
            "version": get_version() or "unknown",
        }

        # Get additional service details if needed
        try:
            status_result = subprocess.run(
                ["systemctl", "status", "mosquitto", "--no-pager", "--lines=0"],
                capture_output=True,
                text=True,
            )

            # Extract additional info from status output
            for line in status_result.stdout.split("\n"):
                line = line.strip()
                if "Active:" in line:
                    status_info["active-since"] = line.split("Active:")[1].strip()
                elif "Main PID:" in line:
                    status_info["main-pid"] = line.split("Main PID:")[1].strip()
        except subprocess.SubprocessError:
            pass  # Additional details are optional

        return status_info

    except Exception:
        logger.exception("Failed to get Mosquitto status")
        return {"service-status": "unknown", "error": "Failed to get status"}


def backup(backup_name: str | None = None) -> str:
    """Create a backup of Mosquitto data and configuration."""
    with tracer.start_as_current_span("mosquitto_backup_operation"):
        span = opentelemetry.trace.get_current_span()

        if backup_name is None:
            backup_name = f"mosquitto-{datetime.datetime.now().strftime('%Y%m%d-%H%M%S')}"

        backup_path = MOSQUITTO_BACKUP_DIR / backup_name
        backup_path.mkdir(parents=True, exist_ok=True)

        span.set_attribute("backup.name", backup_name)
        span.set_attribute("backup.path", str(backup_path))
        logger.info(f"Creating backup: {backup_name}")
        span.add_event("Starting backup operation")

        # Stop service for consistent backup
        stop()
        span.add_event("Service stopped for backup")

        try:
            # Backup configuration
            config_backup = backup_path / "config"
            config_backup.mkdir(exist_ok=True)
            shutil.copy2(MOSQUITTO_CONFIG_PATH, config_backup)
            span.add_event("Configuration backed up")

            # Backup authentication files if they exist
            if MOSQUITTO_AUTH_DIR.exists():
                shutil.copytree(MOSQUITTO_AUTH_DIR, config_backup / "auth", dirs_exist_ok=True)
                span.add_event("Authentication files backed up")

            # Backup certificates if they exist
            if MOSQUITTO_CERTS_DIR.exists():
                shutil.copytree(MOSQUITTO_CERTS_DIR, config_backup / "certs", dirs_exist_ok=True)
                span.add_event("Certificates backed up")

            # Backup persistent data
            if MOSQUITTO_DATA_DIR.exists():
                data_backup = backup_path / "data"
                shutil.copytree(MOSQUITTO_DATA_DIR, data_backup, dirs_exist_ok=True)
                span.add_event("Persistent data backed up")

            # Create backup metadata
            metadata = backup_path / "metadata.txt"
            metadata.write_text(
                f"Backup created: {datetime.datetime.now().isoformat()}\n"
                f"Mosquitto version: {get_version()}\n"
                f"Backup name: {backup_name}\n"
            )
            span.add_event("Backup metadata created")

            logger.info(f"Backup completed: {backup_path}")
            span.add_event("Backup operation completed successfully")
            return str(backup_path)

        finally:
            # Restart service
            start()
            span.add_event("Service restarted after backup")


def restore(backup_name: str) -> None:
    """Restore from a backup."""
    backup_path = MOSQUITTO_BACKUP_DIR / backup_name

    if not backup_path.exists():
        raise RuntimeError(f"Backup not found: {backup_name}")

    logger.info(f"Restoring from backup: {backup_name}")

    # Stop service
    stop()

    try:
        # Restore configuration
        config_backup = backup_path / "config"
        if (config_backup / "mosquitto.conf").exists():
            shutil.copy2(config_backup / "mosquitto.conf", MOSQUITTO_CONFIG_PATH)

        # Restore authentication files
        auth_backup = config_backup / "auth"
        if auth_backup.exists():
            if MOSQUITTO_AUTH_DIR.exists():
                shutil.rmtree(MOSQUITTO_AUTH_DIR)
            shutil.copytree(auth_backup, MOSQUITTO_AUTH_DIR)

        # Restore certificates
        certs_backup = config_backup / "certs"
        if certs_backup.exists():
            if MOSQUITTO_CERTS_DIR.exists():
                shutil.rmtree(MOSQUITTO_CERTS_DIR)
            shutil.copytree(certs_backup, MOSQUITTO_CERTS_DIR)

        # Restore persistent data
        data_backup = backup_path / "data"
        if data_backup.exists():
            if MOSQUITTO_DATA_DIR.exists():
                shutil.rmtree(MOSQUITTO_DATA_DIR)
            shutil.copytree(data_backup, MOSQUITTO_DATA_DIR)

        # Fix ownership
        subprocess.run(
            ["chown", "-R", "mosquitto:mosquitto", str(MOSQUITTO_DATA_DIR)],
            check=True,
            capture_output=True,
        )
        subprocess.run(
            ["chown", "-R", "mosquitto:mosquitto", str(MOSQUITTO_AUTH_DIR)],
            check=True,
            capture_output=True,
        )
        subprocess.run(
            ["chown", "-R", "mosquitto:mosquitto", str(MOSQUITTO_CERTS_DIR)],
            check=True,
            capture_output=True,
        )

        logger.info(f"Restore completed from: {backup_name}")

    finally:
        # Restart service
        start()


def generate_client_cert(client_name: str, output_path: str) -> dict[str, str]:
    """Generate client certificate for MQTT authentication."""
    output_dir = pathlib.Path(output_path)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Check if CA exists
    ca_cert = MOSQUITTO_CERTS_DIR / "ca.crt"
    ca_key = MOSQUITTO_CERTS_DIR / "ca.key"

    if not ca_cert.exists() or not ca_key.exists():
        raise RuntimeError("CA certificate not found. TLS must be configured first.")

    # Generate client private key
    client_key_path = output_dir / f"{client_name}.key"
    subprocess.run(
        ["openssl", "genrsa", "-out", str(client_key_path), "2048"],
        check=True,
        capture_output=True,
    )

    # Generate certificate signing request
    with tempfile.NamedTemporaryFile(mode="w", suffix=".csr", delete=False) as csr_file:
        csr_path = csr_file.name

    try:
        subprocess.run(
            [
                "openssl",
                "req",
                "-new",
                "-key",
                str(client_key_path),
                "-out",
                csr_path,
                "-subj",
                f"/CN={client_name}",
            ],
            check=True,
            capture_output=True,
        )

        # Sign the certificate
        client_cert_path = output_dir / f"{client_name}.crt"
        subprocess.run(
            [
                "openssl",
                "x509",
                "-req",
                "-in",
                csr_path,
                "-CA",
                str(ca_cert),
                "-CAkey",
                str(ca_key),
                "-CAcreateserial",
                "-out",
                str(client_cert_path),
                "-days",
                "365",
            ],
            check=True,
            capture_output=True,
        )

        # Copy CA certificate for client use
        client_ca_path = output_dir / f"{client_name}-ca.crt"
        shutil.copy2(ca_cert, client_ca_path)

        logger.info(f"Generated client certificate for: {client_name}")

        return {
            "cert": str(client_cert_path),
            "key": str(client_key_path),
            "ca": str(client_ca_path),
        }

    finally:
        # Clean up CSR file
        os.unlink(csr_path)


def remove_tls_config() -> None:
    """Remove TLS configuration and certificates."""
    logger.info("Removing TLS configuration")

    # Remove certificate directory
    if MOSQUITTO_CERTS_DIR.exists():
        shutil.rmtree(MOSQUITTO_CERTS_DIR)

    # Recreate empty directory
    MOSQUITTO_CERTS_DIR.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["chown", "-R", "mosquitto:mosquitto", str(MOSQUITTO_CERTS_DIR)],
        check=True,
        capture_output=True,
    )


def setup_password_auth(users: dict[str, str]) -> None:
    """Set up password-based authentication."""
    logger.info("Setting up password authentication")

    password_file = MOSQUITTO_AUTH_DIR / "passwd"

    # Create password file
    with tempfile.NamedTemporaryFile(mode="w", delete=False) as temp_file:
        temp_path = temp_file.name

    try:
        # Generate password file
        for username, password in users.items():
            subprocess.run(
                ["mosquitto_passwd", "-b", temp_path, username, password],
                check=True,
                capture_output=True,
            )

        # Move to final location
        shutil.move(temp_path, password_file)

        # Set permissions
        subprocess.run(
            ["chown", "mosquitto:mosquitto", str(password_file)],
            check=True,
            capture_output=True,
        )
        subprocess.run(
            ["chmod", "600", str(password_file)],
            check=True,
            capture_output=True,
        )

        logger.info(f"Password file created with {len(users)} users")

    finally:
        # Clean up temp file if it still exists
        if pathlib.Path(temp_path).exists():
            os.unlink(temp_path)


def setup_acl(acl_rules: list[str]) -> None:
    """Set up ACL-based authorization."""
    logger.info("Setting up ACL authorization")

    acl_file = MOSQUITTO_AUTH_DIR / "acl"

    # Write ACL rules
    acl_content = "\n".join(acl_rules) + "\n"
    acl_file.write_text(acl_content)

    # Set permissions
    subprocess.run(
        ["chown", "mosquitto:mosquitto", str(acl_file)],
        check=True,
        capture_output=True,
    )
    subprocess.run(
        ["chmod", "644", str(acl_file)],
        check=True,
        capture_output=True,
    )

    logger.info(f"ACL file created with {len(acl_rules)} rules")


def setup_prometheus_metrics(metrics_port: int = 9090) -> None:
    """Set up Prometheus metrics collection for Mosquitto."""
    logger.info(f"Setting up Prometheus metrics on port {metrics_port}")

    # Create simple metrics exporter script
    metrics_script = pathlib.Path("/usr/local/bin/mosquitto-metrics-exporter")

    # Simple metrics script content
    script_content = '''#!/usr/bin/env python3
"""Simple Mosquitto metrics exporter for Prometheus."""

import http.server
import socketserver
import subprocess


class MetricsHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/metrics":
            metrics = self.collect_metrics()
            self.send_response(200)
            self.send_header("Content-type", "text/plain")
            self.end_headers()
            self.wfile.write(metrics.encode())
        else:
            self.send_response(404)
            self.end_headers()

    def collect_metrics(self) -> str:
        """Collect Mosquitto metrics and format for Prometheus."""
        metrics = []

        # Service status metric
        try:
            # Note: This runs inside the metrics script, so we use subprocess for systemctl
            result = subprocess.run(
                ["systemctl", "is-active", "mosquitto"],
                capture_output=True, text=True
            )
            service_up = 1 if result.returncode == 0 else 0
            metrics.append(f"mosquitto_service_up {service_up}")
        except Exception:
            metrics.append("mosquitto_service_up 0")

        # Connection count
        try:
            result = subprocess.run(
                ["ss", "-tn", "sport", "=", ":1883"],
                capture_output=True, text=True
            )
            count = len([line for line in result.stdout.split("\\n") if ":1883" in line]) - 1
            connection_count = max(0, count)
            metrics.append(f"mosquitto_connections_current {connection_count}")
        except Exception:
            metrics.append("mosquitto_connections_current 0")

        # Format as Prometheus metrics
        output = []
        output.append("# HELP mosquitto_service_up Whether Mosquitto service is running")
        output.append("# TYPE mosquitto_service_up gauge")
        output.append("# HELP mosquitto_connections_current Current client connections")
        output.append("# TYPE mosquitto_connections_current gauge")
        output.extend(metrics)
        output.append("")

        return "\\n".join(output)


if __name__ == "__main__":
    PORT = METRICS_PORT_PLACEHOLDER
    with socketserver.TCPServer(("", PORT), MetricsHandler) as httpd:
        print(f"Serving Mosquitto metrics at port {PORT}")
        httpd.serve_forever()
'''

    # Replace placeholder with actual port
    final_content = script_content.replace("METRICS_PORT_PLACEHOLDER", str(metrics_port))

    # Write the script
    metrics_script.write_text(final_content)
    metrics_script.chmod(0o755)

    # Create systemd service
    service_content = """[Unit]
Description=Mosquitto Prometheus Metrics Exporter
After=mosquitto.service
Requires=mosquitto.service

[Service]
Type=simple
User=mosquitto
Group=mosquitto
ExecStart=/usr/local/bin/mosquitto-metrics-exporter
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
"""

    service_path = pathlib.Path("/etc/systemd/system/mosquitto-metrics.service")
    service_path.write_text(service_content)

    # Start the service
    systemd.daemon_reload()
    systemd.service_enable("mosquitto-metrics")
    systemd.service_start("mosquitto-metrics")

    logger.info(f"Prometheus metrics exporter started on port {metrics_port}")


def remove_prometheus_metrics() -> None:
    """Remove Prometheus metrics configuration."""
    logger.info("Removing Prometheus metrics configuration")

    try:
        # Stop and disable metrics service
        systemd.service_stop("mosquitto-metrics")
        systemd.service_disable("mosquitto-metrics")

        # Remove service file
        service_path = pathlib.Path("/etc/systemd/system/mosquitto-metrics.service")
        if service_path.exists():
            service_path.unlink()

        # Remove metrics script
        metrics_script = pathlib.Path("/usr/local/bin/mosquitto-metrics-exporter")
        if metrics_script.exists():
            metrics_script.unlink()

        # Reload systemd
        systemd.daemon_reload()

        logger.info("Prometheus metrics configuration removed")
    except Exception as e:
        logger.warning(f"Error removing metrics configuration: {e}")


def get_metrics_status() -> dict[str, str]:
    """Get status of Prometheus metrics exporter."""
    try:
        is_running = systemd.service_running("mosquitto-metrics")
        status = "active" if is_running else "inactive"

        # Get port information
        port_info = "unknown"
        try:
            port_result = subprocess.run(
                ["ss", "-tlnp", "|", "grep", ":9090"], shell=True, capture_output=True, text=True
            )
            if port_result.returncode == 0 and port_result.stdout:
                port_info = "9090"
        except Exception:
            pass

        return {
            "metrics-service-status": status,
            "metrics-port": port_info,
            "metrics-endpoint": f"http://localhost:{port_info}/metrics"
            if port_info != "unknown"
            else "unavailable",
        }

    except subprocess.SubprocessError:
        logger.exception("Failed to get metrics status")
        return {"metrics-service-status": "unknown", "error": "Failed to get metrics status"}
